
version: "3.8"
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: rohitxten/flight_price_backend:latest
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=flightdb
      - MODEL_PATH=/app/model.pkl
    ports:
      - "5000:5000"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    image: rohitxten/flight_price_frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
